modLoader="javafml"
loaderVersion="47.1.3" # Replace with actual loader version
license="YOUR_LICENSE" # Replace with your mod's license

[[mods]]
modId="archimedesfluids" # Replace with your mod's ID
version="1.5dev" # Replace with your mod's version
displayName="Archimedes Fluids" # Replace with your mod's display name
authors="YOUR_NAME" # Optional: Replace with author's name(s)
description='''
YOUR_MOD_DESCRIPTION
''' # Replace with your mod's description

[[dependencies.YOUR_MOD_ID]]
modId="forge"
mandatory=true
versionRange="47.1.3" # Replace with Forge version range
ordering="NONE"
side="BOTH"

[[dependencies.YOUR_MOD_ID]]
modId="minecraft"
mandatory=true
versionRange="1.20.1" # Replace with Minecraft version range
ordering="NONE"
side="BOTH"
